### ISSUE TITLE
BitVec::iter().rev().take(N).rev() segfaults

### ISSUE THREAD

**Issue by Cryptjar** [myrrlyn/bitvec#77]
The following code snippet just **segfaults**!

```rust
fn main() {
    use bitvec::vec::BitVec;

    // The argument of `take`. If above "SOME" threshold, it will panic!
    // If below "the" threshold, the assert will fail instead.
    //
    // It appears that the threshold for normal execution is 4,
    // but when executing the binary via `gdb` it is 6.
    const N: usize = 6;

    let mut bv: BitVec = BitVec::new();
    // Must be at least the 'register size', but may be much larger
    bv.resize(64, true);

    // Here the complete iter-rev-take-rev-sequence is mandatory to reproduce the error,
    // just the `collect` is here for convenience.
    let last_few: Vec<_> = bv.iter().rev().take(N).rev().collect();

    // Also notice, `bv` only contains `true`, but with `N` < 4, the `last_few` are all `false`!!!
    assert_eq!(&[&true; N], last_few.as_slice());
}
```

It seems that this is quite a corner case as several preconditions have to be meet. Also, I didn't check whether this error is specific to `BitVec` or applies to other types as well. All I can say is that [`access::BitAccess::get_bit`](https://github.com/myrrlyn/bitvec/blob/develop/src/access.rs#L192) or [`slice::iter::Iter::pop_front`](https://github.com/myrrlyn/bitvec/blob/develop/src/slice/iter.rs#L164) are the only `unsafe` pieces in the stack trace, so either (or both) of them seam to be unsound.

Also notice, as mentioned in above snippet comments, there are also cases where the program does not segfault but instead gives the wrong result. Maybe, indicating a more general bug somewhere in the code.

---

For reference here the complete stack trace:
```none
Program received signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x000055555556b069 in core::cell::Cell<T>::get (self=0x5555554e0ce8) at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/cell.rs:431
#1  0x000055555555c0b4 in <core::cell::Cell<usize> as radium::Radium<usize>>::load (self=0x5555554e0ce8) at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/radium-0.3.0/src/lib.rs:436
#2  0x000055555555bec0 in bitvec::access::BitAccess::load_value (self=0x5555554e0ce8) at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.19.0/src/access.rs:326
#3  0x000055555555bee8 in bitvec::access::BitAccess::get_bit (self=0x5555554e0ce8, index=...) at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.19.0/src/access.rs:192
#4  0x0000555555561ca1 in bitvec::slice::iter::Iter<O,T>::pop_front (self=0x7fffffffd378) at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.19.0/src/slice/iter.rs:164
#5  0x0000555555561e71 in <bitvec::slice::iter::Iter<O,T> as core::iter::traits::iterator::Iterator>::nth (self=0x7fffffffd378, n=18446744073702025216)
    at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.19.0/src/slice/iter.rs:496
#6  0x0000555555563cc3 in <core::iter::adapters::Rev<I> as core::iter::traits::double_ended::DoubleEndedIterator>::nth_back (self=0x7fffffffd378, n=18446744073702025216)
    at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/adapters/mod.rs:98
#7  0x0000555555563d4e in <core::iter::adapters::Take<I> as core::iter::traits::double_ended::DoubleEndedIterator>::next_back (self=0x7fffffffd378)
    at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/adapters/mod.rs:2289
#8  0x000055555556408e in <core::iter::adapters::Rev<I> as core::iter::traits::iterator::Iterator>::next (self=0x7fffffffd378)
    at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/iter/adapters/mod.rs:49
```

**Comment by myrrlyn** [comment]
*oops*. I will comment again when I publish the fix to crates.io
