### ISSUE TITLE
Error creating BitVec with a storage type distinct than u8

### ISSUE THREAD

**Issue by torce** [myrrlyn/bitvec#9]
I'm trying to return an initialized `BitVec` from a function using the `bitvec!` macro in a `no_std` crate. It fails for any storage type except `u8`.

```rust
// lib.rs
#![no_std]
extern crate bitvec;

use bitvec::prelude::*;

fn error<T: Bits>() -> BitVec<BigEndian, T> {
    bitvec![BigEndian, T; 0; 8] // It fails for any length
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error() {
        error::<u8>(); // Only this one works
        error::<u16>();
        error::<u32>();
        error::<u64>();
    }
}
```

```toml
# Cargo.toml
[package]
name = "error"
version = "0.1.0"
authors = ["david"]
edition = "2018"

[lib]
name = "error"
path = "src/lib.rs"

[dependencies.bitvec]
git = "https://github.com/myrrlyn/bitvec"
branch = "master"
default-features = false
features = ["alloc"]
```

```toml
# Cargo.lock
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
[[package]]
name = "bitvec"
version = "0.11.0"
source = "git+https://github.com/myrrlyn/bitvec#896c71a34724b9153130d374fc4dc9b170c107a8"

[[package]]
name = "error"
version = "0.1.0"
dependencies = [
 "bitvec 0.11.0 (git+https://github.com/myrrlyn/bitvec)",
]

[metadata]
"checksum bitvec 0.11.0 (git+https://github.com/myrrlyn/bitvec)" = "<none>"
```

Backtrace:

```
---- error::tests::test_error stdout ----
thread 'error::tests::test_error' panicked at 'attempt to shift left with overflow', /home/david/.cargo/git/checkouts/bitvec-de08e8e455d8f2a6/896c71a/src/bits.rs:237:26
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: bitvec::bits::Bits::set_at
             at /home/david/.cargo/git/checkouts/bitvec-de08e8e455d8f2a6/896c71a/src/bits.rs:237
  10: bitvec::bits::Bits::set
             at /home/david/.cargo/git/checkouts/bitvec-de08e8e455d8f2a6/896c71a/src/bits.rs:179
  11: bitvec::slice::BitSlice<C,T>::set
             at /home/david/.cargo/git/checkouts/bitvec-de08e8e455d8f2a6/896c71a/src/slice.rs:474
  12: bitvec::vec::BitVec<C,T>::push
             at /home/david/.cargo/git/checkouts/bitvec-de08e8e455d8f2a6/896c71a/src/vec.rs:889
  13: <bitvec::vec::BitVec<C,T> as core::iter::traits::collect::FromIterator<bool>>::from_iter
             at /home/david/.cargo/git/checkouts/bitvec-de08e8e455d8f2a6/896c71a/src/vec.rs:1974
  14: core::iter::traits::iterator::Iterator::collect
             at /rustc/e938c2b9aae7e0c37c382e4e22bdc360e9a4f0b6/src/libcore/iter/traits/iterator.rs:1465
  15: hamming_code::error::error
             at src/error.rs:6
  16: hamming_code::error::tests::test_error
             at src/error.rs:17
  17: hamming_code::error::tests::test_error::{{closure}}
             at src/error.rs:15
  18: core::ops::function::FnOnce::call_once
             at /rustc/e938c2b9aae7e0c37c382e4e22bdc360e9a4f0b6/src/libcore/ops/function.rs:231
  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/e938c2b9aae7e0c37c382e4e22bdc360e9a4f0b6/src/liballoc/boxed.rs:704
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  21: test::run_test::run_test_inner::{{closure}}
             at /rustc/e938c2b9aae7e0c37c382e4e22bdc360e9a4f0b6/src/libstd/panicking.rs:272
             at /rustc/e938c2b9aae7e0c37c382e4e22bdc360e9a4f0b6/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1468

```

**Comment by myrrlyn** [comment]
I do not know how to create a working `#![no_std]` + `#![feature(alloc)]` executable, so I am not able to reproduce the error directly. However, upon inspection, I *believe* I have found the cause of the failure.

Please let me know if commit #90b6008 addresses the problem?

**Comment by torce** [comment]
Thank you for your answer (and for your work on this crate :smile: ).
I have repeated the tests with that commit and it seems ok. 
I have tried also to create them with different values ans storage types and the values are ok too.
Regards.

**Comment by myrrlyn** [comment]
Excellent, thank you for the followup! Thank you also for the backtrace; the panic site and message told me directly where to go, and I probably wouldn't have seen the problem as quickly without them.
